services:
    redis: 
        image: redis/redis-stack-server
        ports:
            - '6379:6379'
    flask:
        build:
            context: ./server
            dockerfile: Dockerfile
        stop_signal: SIGINT
        ports:
            - '8000:8000'
        depends_on:
            - redis
    web:
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        ports:
            - '3000:3000'
        depends_on:
            - flask